name: azkar
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  adhan: ^2.0.0-nullsafety.2
  assets_audio_player: ^3.0.5
  circular_bottom_navigation: ^2.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_compass: ^0.7.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  location: ^4.4.0
  shared_preferences: ^2.0.15
  system_alert_window: ^1.2.0
  workmanager: ^0.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.11

flutter_native_splash:
  android: true
  ios: true
  web: false
  fullscreen: false
  color: '#ffffff'
  image: 'assets/images/splash-logo.png'
  android_12:
    color: '#ffffff'
    image: 'assets/images/splash-logo.png'



flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/json/
    - assets/audio/
    - assets/

  fonts:
    - family: A-Hemmat
      fonts:
        - asset: assets/fonts/al-hemmat.ttf

    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf

    - family: Aldhabi
      fonts:
        - asset: assets/fonts/aldhabi.ttf

    - family: QuranSurah
      fonts:
        - asset: assets/fonts/QuranSurah.ttf

        